app_front_contact:
    path: /
    controller: App\Controller\FrontController::contact
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
